### ISSUE TITLE
Small bug when destroying a cluster that has been faulty configured

### ISSUE THREAD

**Issue by iblanque** [grycap/ec3#36]
In the last version of IM/EC3, if the installation of the internal IM fails, the destroy command fails from outside, so you have to destroy the front end manually.

This is not an imporant bug, but just to be taken into consideration in further versions.

**Comment by amcaar** [comment]
If the internal IM fails, the destroy operation of EC3 will fail, because it contacts with the internal IM to destroy the cluster.

We have recently changed the behaviour of the destroy operation. Before, the cluster "auto-killed" itself, by calling the destroy operation to the internal IM, but this solution generated problems with providers like Amazon EC2. Now, we perform an import of the infrastructure from the external IM, in order to destroy better the cluster form the outside. But, if the internal IM cannot perform an export operation, the destroy operation will fail.

We will take into account the problem that you found for future versions.

**Comment by micafer** [comment]
Hi @amcaar,

In the @iblanque case the problem was that the internal IM has not been installed, due to network issues, and the infrastructure has never been transferred to the interal IM and it remains in the external one (the default one at our UPV instance).
Im this case the ec3 tool has check it the infrastructure is still in the external IM server and try to delete from it.

**Comment by amcaar** [comment]
I added a snippet of code considering this issue to the EC3 client. @micafer @iblanque can you check if this solves the problem?
